# testbench
DnCNN_tb.v
sram_model/SRAM_activation_32768x32b.v
sram_model/SRAM_weight_4096x32b.v

# netlist generated by Design Compiler
../syn/netlist/DnCNN_syn.v
# Logic Gate models
-v /theda21_2/library/GPDK045/cur/gsclib045/verilog/slow_vdd1v2_basicCells.v

+define+GATESIM
+access+r
